### ISSUE TITLE
can't establish a tunnel

### ISSUE THREAD

**Issue by evanrich** [STRRL/cloudflare-tunnel-ingress-controller#119]
suddenly the cloudflared-connector is throwing errors and wont establish a tunnel:

```
-09-11T21:31:09Z ERR Register tunnel error from server side error="Unauthorized: Failed to get tunnel" connIndex=0 event=0 ip=198.41.192.77
2024-09-11T21:31:09Z INF Retrying connection in up to 1m4s connIndex=0 event=0 ip=198.41.192.77
2024-09-11T21:31:15Z ERR failed to serve incoming request error="Unauthorized: Failed to get tunnel"
2024-09-11T21:31:15Z ERR Register tunnel error from server side error="Unauthorized: Failed to get tunnel" connIndex=0 event=0 ip=198.41.192.77
2024-09-11T21:31:15Z INF Retrying connection in up to 1m4s connIndex=0 event=0 ip=198.41.192.77
2024-09-11T21:31:42Z ERR failed to serve incoming request error="Unauthorized: Failed to get tunnel"
2024-09-11T21:31:42Z ERR Register tunnel error from server side error="Unauthorized: Failed to get tunnel" connIndex=0 event=0 ip=198.41.192.77
2024-09-11T21:31:42Z INF Retrying connection in up to 1m4s connIndex=0 event=0 ip=198.41.192.77
```
![image](https://github.com/user-attachments/assets/9e2b90a1-7922-4a78-bfe0-f4a9304fefec)

i've tried using the master api token as well as one created with the appropriate permissions,  anyone know whats up?  

If i run this from a command line, the tunnel is estabished correct:

```
docker run cloudflare/cloudflared:latest tunnel --no-autoupdate run --token eyJ............................................................................
```
![image](https://github.com/user-attachments/assets/7c37a8f6-0ff3-4049-9f39-78076399c403)

**Comment by evanrich** [comment]
hmm.. for some reason, running the help command works, but not using argo with the same config...I'll have to dig into it

**Comment by STRRL** [comment]
Thanks @evanrich  for pointing this out! Actually, I have no idea why it dose not work... Maybe try to generate a new API token? 😂

I am looking forward to your investigating result, please let us know if you find something! Thanks!

**Comment by evanrich** [comment]
Will do, It was working fine till i noticed that the chart wasn't updating the cloudflared image, i was stuck on 2024.6.1, so i bumped it to 2024.9.1 , but then rolled back when it didn't work.  I also tried using my cloudflare global api key as well since the errors looked like a permission issue but that doesn't work either.

This was working fine for months until today.   Given that the `helm install` command works`, even tho im not doing anything different in my values file, I'll strip down my values to just the bare minimum and try from scratch. This is what I was using:

```
cloudflare:
  secretRef:
    name: cloudflare-tunnel-credentials
    accountIDKey: account_id
    tunnelNameKey: tunnel_name
    apiTokenKey: api_token

ingressClass:
  name: cloudflare-tunnel
  controllerValue: strrl.dev/cloudflare-tunnel-ingress-controller
  isDefaultClass: false

replicaCount: 2

image:
  repository: ghcr.io/strrl/cloudflare-tunnel-ingress-controller
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

resources:
   limits:
     cpu: 100m
     memory: 128Mi
   requests:
     cpu: 30m
     memory: 64Mi

cloudflared:
  image:
    repository: cloudflare/cloudflared
    pullPolicy: IfNotPresent
    tag: 2024.9.1
```

**Comment by evanrich** [comment]
OK @STRRL  I'll mark this closed, re-deploying it from scratch works, although I removed the securityContext settings for now thinking maybe that was it.  I'll play around with it.  One thing i noticed is that along with not upgrading the cloudflared image correctly, when you do a helm uninstall, it does not remove the cloudflared container, only the tunnel ingress controller one.   Thanks!
