### ISSUE TITLE
Feature request: Add ServiceMonitor

### ISSUE THREAD

**Issue by z0rc** [STRRL/cloudflare-tunnel-ingress-controller#127]
In many cases prom configuration is managed by [prometheus-operator](https://github.com/prometheus-operator/prometheus-operator), which uses [ServiceMonitor](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/getting-started.md) custom resources to setup prom scraping targets.

Please add ability to deploy ServiceMonitor as part of helm chart.

Important thing to keep in mind. When ServiceMonitor is enabled, Service must not have prometheus scraping annotations set. As this may cause double scrape in some configurations.

**Comment by STRRL** [comment]
That sounds great! Thanks!

Do you have interest in coding it? Or would I write the code and invite you to make a review? Which one do you prefer?

**Comment by z0rc** [comment]
Yeah, I can submit a PR for this.

**Comment by STRRL** [comment]
> Yeah, I can submit a PR for this.

That's great! Thanks a lot! ❤️ 🚀
