### ISSUE TITLE
Unable to setup tunnel

### ISSUE THREAD

**Issue by Evantage-WS** [STRRL/cloudflare-tunnel-ingress-controller#134]
Hi, 

I am using your 0.0.13 version, but the tunnel is not created, I do see this error in the controller. Any idea what could be wrong?

Thanks
```
2024-10-15T09:50:29Z ERR Failed to serve quic connection error="context canceled" connIndex=3 event=0 ip=198.41.192.27
2024-10-15T09:50:29Z INF Retrying connection in up to 1m4s connIndex=3 event=0 ip=198.41.192.27
```

**Comment by z0rc** [comment]
Most likely default tunnel's QUIC protocol doesn't work with your environment/network. For now there is no way to override tunnel protocol, you can follow https://github.com/STRRL/cloudflare-tunnel-ingress-controller/issues/72.

**Comment by STRRL** [comment]
Thanks for awesome #72 from @omegazeng, and release v0.0.14 is on the way:

https://github.com/STRRL/cloudflare-tunnel-ingress-controller/releases/tag/v0.0.14

**Comment by STRRL** [comment]
Hi @Evantage-WS, please try our new version, please let us know whether it works for you! 🔥 Feel free to leave comments or open new issues if you have other ideas or problems! Thanks!

Also thanks to @z0rc for your warmly explaination. 🥰
