### ISSUE TITLE
kubernete headless service

### ISSUE THREAD

**Issue by Auggie321** [STRRL/cloudflare-tunnel-ingress-controller#2]
Q:  The service of headless service cannot be forwarded by normal tunnel ？

```
root@agub20 ~ $ kubectl get svc -n loki |grep loki-grafana
loki-grafana      ClusterIP   10.68.133.227   <none>        80/TCP     171d

root@agub20 ~ $ kubectl get svc -n gitea |grep gitea-http
gitea-http            ClusterIP   None            <none>        3000/TCP    64d

root@agub20 ~ $ kubectl version 
Client **{Major:"1", Minor:"23", GitVersion:"v1.23.1", **, GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server**{Major:"1", Minor:"23", GitVersion:"v1.23.1", **, GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
```
---
headless service failed
```
kubectl -n gitea \
  create ingress dashboard-via-cf-tunnel2 \
  --rule="k8s2.aug****.top/*=gitea-http:3000"\
  --class cloudflare-tunnel
```
`failure log`
`kubectl logs -f --tail=20 -n cloudflare-tunnel-ingress-controller controlled-cloudflared-connector-5466477ddb-9p97n `
```
2023-06-15T09:01:28Z ERR  error="Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared: dial tcp: lookup None on 169.254.20.10:53: no such host" cfRay=7d79a0df3b5a8889-LHR event=1 ingressRule=0 originService=http://None:3000
2023-06-15T09:01:28Z ERR Request failed error="Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared: dial tcp: lookup None on 169.254.20.10:53: no such host" connIndex=3 dest=https://k8s2.aug***.top/ event=0 ip=198.41.200.43 type=http
2023-06-15T09:01:29Z ERR  error="Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared: dial tcp: lookup None on 169.254.20.10:53: no such host" cfRay=7d79a0f10a558889-LHR event=1 ingressRule=0 originService=http://None:3000
```
try again,
```
root@axxx ~ $ kubectl -n gitea \
>   create ingress dashboard-via-cf-tunnel2 \
>   --rule="k8s2.au***.top/*=gitea-http.gitea.svc.cluster.local:3000"\
>   --class cloudflare-tunnel

error: rule k8s2.au***.top/*=gitea-http.gitea.svc.cluster.local:3000 is invalid and should be in format host/path=svcname:svcport[,tls[=secret]]
```

---

successfully
```
kubectl -n loki \
  create ingress dashboard-via-cf-tunnel3 \
  --rule="k8s3.aug***.top/*=loki-grafana:80"\
  --class cloudflare-tunnel
```

**Comment by STRRL** [comment]
Headless Service is mainly used to discover stateful workloads like pods in `StatefulSet`, and there is no `ClusterIP` provided.

For most Ingress Controller, headless service is NOT supported for exposing HTTP services. Ingress always requires the `Spec.ClusterIP` in Service.

But there are some solutions you could take try:

- If your application is stateless,  you could crate **another** `ClusterIP` service for exposing services.
- If you application is stateful, and you want to expose a certain pod, you could create **another** `ExternalName` service with the FQDN of the target pod.

**Comment by STRRL** [comment]
Currently this controller would still use `None` as the hostname of ingress upstream. It's better to make it fail-fast, throw error when a Headless Service occurs.

**Comment by STRRL** [comment]
> Currently this controller would still use `None` as the hostname of ingress upstream. It's better to make it fail-fast, throw error when a Headless Service occurs.

carried by v0.0.3: https://github.com/STRRL/cloudflare-tunnel-ingress-controller/releases/tag/v0.0.3

**Comment by Auggie321** [comment]
Thank you for your reply.
Although nginx-ingress can access gitea using the following configuration external forwarding.
```yaml
annotations:
  kubernetes.io/ingress.class: nginx
  nginx.ingress.kubernetes.io/ssl-redirect: "true"
```


This can also be achieved by using the deployment nginx instance configuration redirection.

will continue to explore other, better ways to handle this later.

**Comment by STRRL** [comment]
> Thank you for your reply. Although nginx-ingress can access gitea using the following configuration external forwarding.
> 
> ```yaml
> annotations:
>   kubernetes.io/ingress.class: nginx
>   nginx.ingress.kubernetes.io/ssl-redirect: "true"
> ```
> 
> This can also be achieved by using the deployment nginx instance configuration redirection.
> 
> will continue to explore other, better ways to handle this later.

I am not so sure about how ingress-nginx provides features like "Ingress on Headless Services" 🤔

I found these codes in ingress-nginx, and it seems ingress-nginx do not resolve the headless service:

https://github.com/kubernetes/ingress-nginx/blob/30de5999c15fb0dc1581950685f1e027957515d5/internal/ingress/controller/controller.go#L1136

It you have some idea about this feature or improvement, feel free to keep discussing, or open a PR! 

Thanks! :heart:
