### ISSUE TITLE
Add ARM docker image

### ISSUE THREAD

**Issue by guilhermewolf** [STRRL/cloudflare-tunnel-ingress-controller#34]

**Comment by kanya-approve** [comment]
#45

**Comment by kanya-approve** [comment]
Until this is merged, you can use 

repository: ghcr.io/kanya-approve/cloudflare-tunnel-ingress-controller
tag: master

**Comment by kanya-approve** [comment]
The new image has ARM support. I deleted my fork. You can remove image.repository and image.tag from your values.yaml.
