### ISSUE TITLE
Add a value to customise cloudflared's `--protocol` flag

### ISSUE THREAD

**Issue by sportshead** [STRRL/cloudflare-tunnel-ingress-controller#72]
QUIC does not work in certain environments, while `http2` is more reliable. A configuration value to change the `--protocol` flag to `http2` or others would be quite helpful.

See: https://github.com/cloudflare/cloudflared/issues/617#issuecomment-1414799233

**Comment by UnstoppableMango** [comment]
It seems like it would be a good idea to allow passing arbitrary args to `cloudflared`. I took a stab at this in a branch and discovered it was kinda annoying to get a yaml list from helm into the controlled deployment.

**Comment by omegazeng** [comment]
same issue.
any update?
I would need this update. thx.

**Comment by STRRL** [comment]
closed by #72
