### ISSUE TITLE
DNS Validation Error (1004)"

### ISSUE THREAD

**Issue by delta-whiplash** [STRRL/cloudflare-tunnel-ingress-controller#73]
Hello I have this error when I try to do the setup like in the youtube video : 
`kubectl -n default create ingress nginx-via-cf-tunnel --rule "nginxcf.delta-net.ovh/*=nginx:80" --class cloudflare-tunnel`

`2024/03/04 12:20:35 controller-runtime: "caller"={"file":"controller.go","line":324} "msg"="Reconciler error" "error"="put exposures: update DNS CNAME record: update DNS CNAME record for zone [delta-net.ovh]: create DNS record for zone delta-net.ovh, hostname nginxcf.delta-net.ovh: DNS Validation Error (1004)" "controller"="ingress" "controllerGroup"="networking.k8s.io" "controllerKind"="Ingress" "Ingress"={"name":"nginx-via-cf-tunnel","namespace":"default"} "namespace"="default" "name"="nginx-via-cf-tunnel" "reconcileID"="8f0d1b6b-1422-463f-94e0-d2ed48943f2a"
`

could you help me ?

**Comment by Rekseto** [comment]
I can confirm i have same one

**Comment by delta-whiplash** [comment]
@STRRL do you have a fix or did we do something wrong ?

**Comment by STRRL** [comment]
Hi @delta-whiplash  @Rekseto , it requires you use cloudflare managed domain to setup a tunnel.

If you own the domain `delta-net.ovh`, you could setup it on cloudflare.

**Comment by STRRL** [comment]
I am going to close this issue. Feel free to reopen it if you have other questions.

**Comment by delta-whiplash** [comment]
@STRRL 

This domain is already managed by cloudflare 

All of my tunnels are using it from my old docker instance (with cloudflare tunnel container)
