### ISSUE TITLE
Publish new image and helm chart version?

### ISSUE THREAD

**Issue by diegs** [STRRL/cloudflare-tunnel-ingress-controller#84]
Thanks so much for this great project. It generally works really well, though sometimes I observe some funny behavior that I'm more likely to blame cloudflare on.

Still, it looks like a lot of improvements have been made since the 0.0.9 release in November. Would you mind cutting a new release image and helm chart?

Thanks again.

**Comment by STRRL** [comment]
here we go! 

https://github.com/STRRL/cloudflare-tunnel-ingress-controller/releases/tag/v0.0.10

BTW, there're some new codes that are not well tested, I would keep trying to improve that in the next weeks. 

feel free to open a new issue if you encounter some unexpected behavior!

Thanks!
