### ISSUE TITLE
ClusterIP vs Service FQDN

### ISSUE THREAD

**Issue by iamwillbar** [STRRL/cloudflare-tunnel-ingress-controller#91]
Is there a specific reason why the ClusterIP is used rather than just using the service's FQDN in the Cloudflare tunnel? Since the tunnel is running inside the cluster it should be able to resolve service FQDNs.

**Comment by STRRL** [comment]
there are no other specific reasons to use ClusterIP rather than service FQDN domain, and technically we could implement in both 2 ways and let user to configure that.

**Comment by STRRL** [comment]
I am going to close this issue, if you have any more thoughts, feel free to reopen it.
